#!/bin/bash

docker run -i -t \
    -e TWEET_OAUTH_CONSUMER_KEY="$TWEET_OAUTH_CONSUMER_KEY" \
    -e TWEET_OAUTH_CONSUMER_SECRET="$TWEET_OAUTH_CONSUMER_SECRET" \
    -e TWEET_OAUTH_TOKEN_KEY="$TWEET_OAUTH_TOKEN_KEY" \
    -e TWEET_OAUTH_TOKEN_SECRET="$TWEET_OAUTH_TOKEN_SECRET" \
    -e TWEET_PRODUCER_KAFKA_BROKERS="$TWEET_PRODUCER_KAFKA_BROKERS" \
    -e TWEET_PRODUCER_KAFKA_TOPIC="$TWEET_PRODUCER_KAFKA_TOPIC" \
    pkolloch/tweet-producer jobs
